version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: puckel/docker-airflow:1.10.9
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW_CONN_POSTGRES_DB=postgres://postgres:passw0rd@database:5432/lineman_wongnai
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ${PWD}/airflow/dags:/usr/local/airflow/dags
            - ${PWD}/airflow/plugins:/usr/local/airflow/plugins
            - ${PWD}/airflow/scripts:/usr/local/airflow/scripts
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    database:
          image: postgres:9.6
          environment:
            - POSTGRES_DB=lineman_wongnai
            - POSTGRES_PASSWORD=passw0rd
            - PGDATA=/var/lib/postgresql/data/pgdata
          volumes:
            - ${PWD}/data:/var/lib/postgresql/data/lmwn
          logging:
              options:
                max-size: 10m
                max-file: "3"
    hive:
        image: cloudera/quickstart:latest
        container_name: hive-docker
        restart: always
        depends_on:
            - database
        ports:
            - 8888:8888
            - 10000:10000
            - 7180:7180
            - 8020:8020
        hostname: quickstart.cloudera
        privileged: true
        tty: true
        command: /usr/bin/docker-quickstart
        volumes:
            - ${PWD}/driver/postgresql-42.2.19.jre6.jar:/var/lib/sqoop/postgresql-42.2.19.jre6.jar


  
